include:
  - path:
      - apps/supabase/docker-compose.yml
      - apps/supabase/dev/docker-compose.dev.yml
services:
  katana:
    image: ghcr.io/dojoengine/katana:v1.5.0
    command: katana --silent --explorer --dev --dev.no-fee --http.addr 0.0.0.0 --http.cors_origins "*"
    ports:
      - 5050:5050
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5050"]
      interval: 10s
      timeout: 5s
      retries: 5

  contracts:
    build: apps/contracts
    environment:
      - STARKNET_ACCOUNT=katana-0
      - STARKNET_RPC=http://katana:5050
    depends_on:
      katana:
        condition: service_healthy

  www:
    build:
      context: apps/www
      additional_contexts:
        - root=.
    restart: always
    volumes:
      - ./apps/www:/home/strapex/apps/www
      - /home/strapex/apps/www/.next
      - /home/strapex/apps/www/node_modules
    ports:
      - 3333:3333
    depends_on:
      - contracts
      - storage
